gaepuv/puv/urls.py
from django.conf.urls.defaults import *
from puv import settings

urlpatterns = patterns('',
    (r'^$', 'puv.poll.views.index'),
    (r'^atom.xml', 'puv.poll.views.feed', {'template':'atom.xml'}),
    (r'^polls.rss', 'puv.poll.views.feed', {'template':'polls.rss'}),
    (r'^vote/$', 'puv.poll.views.index', {'template':'vote_index.html'}),
    (r'^results/$', 'puv.poll.views.index', {'template':'results_index.html'}),
    (r'^create/$', 'puv.poll.views.create'),
    (r'^poll/(?P<poll_key>[^\.^/]+)/$', 'puv.poll.views.poll_detail'),
    (r'^poll/(?P<poll_key>[^\.^/]+)/results/$', 'puv.poll.views.poll_results'),
    (r'^poll/(?P<poll_key>[^\.^/]+)/results.xml', 'puv.poll.views.poll_results_xml'),
    #(?P<username>[^\.^/]+)
    )

if settings.DEBUG:
    from django.views.static import serve
    _media_url = settings.MEDIA_URL
    if _media_url.startswith('/'):
        _media_url = _media_url[1:]
        urlpatterns += patterns('',
                               (r'^%s(?P<path>.*)$' % _media_url,
                               serve,
                               {'document_root': settings.MEDIA_ROOT}))
        del(_media_url, serve)

gaepuv/puv/poll/models.py
from google.appengine.ext import db
from django import forms
from django.utils.safestring import mark_safe

class Poll(db.Model):
    """ Top level poll 
        voter flags record voter info
        locations and dates are the number of those types of choices
        GAE doesnt do aggregate funcs - so record them here (last and total votes) 
    """
    question = db.StringProperty()
    private = db.BooleanProperty(default = False)
    anonymous = db.BooleanProperty(default = False)
    onechoice = db.BooleanProperty(default = False)
    locations = db.IntegerProperty(default = 3)
    dates = db.IntegerProperty(default = 0)
    created_on = db.DateTimeProperty(auto_now_add = 1)
    created_by = db.StringProperty()
    last_vote = db.DateTimeProperty(auto_now = 1)
    total_votes = db.IntegerProperty(default = 0)
    user = db.UserProperty()
    email = db.EmailProperty()
    
    def __str__(self):
        return '%s' % self.question
    
    def get_absolute_url(self):
        return mark_safe('/poll/%s/' % self.key())
    
class Choice(db.Model):
    """ Location choices """
    poll = db.ReferenceProperty(Poll)
    choice = db.StringProperty()
    location = db.GeoPtProperty()
    address = db.PostalAddressProperty()
    url = db.LinkProperty()
    votes = db.IntegerProperty(default = 0)

    class Meta:
        ordering = ('-votes',)

    def __str__(self):
        html = ''
        if self.url:
            html = '<a href="%s">' % self.url
        if self.choice:
            html += self.choice
        else: 
            html += self.address
        if self.url:
            html += '</a>'
        return mark_safe(html) 

class DateChoice(db.Model):
    """ Date and/or Time choices - dateortime is
        0 = date, 1 = time, 2 = date and time
    """
    poll = db.ReferenceProperty(Poll)    
    datetime = db.DateTimeProperty()
    dateortime = db.IntegerProperty(default = 0)
    votes = db.IntegerProperty(default = 0)

    class Meta:
        ordering = ('datetime',)

class Voter(db.Model):
    """ Record voter data for polls with anon = False """
    poll = db.ReferenceProperty(Poll)    
    choice = db.ReferenceProperty(Choice)
    datechoice = db.ReferenceProperty(DateChoice)
    created_by = db.StringProperty()
    created_on = db.DateTimeProperty(auto_now_add = 1)
    user = db.UserProperty()

class Country(db.Model):
    """ 2 letter iso code to geocode """
    iso = db.StringProperty()
    location = db.GeoPtProperty()

gaepuv/puv/poll/forms.py
from django import forms
import models
from google.appengine.ext.db import djangoforms
from puv.poll.widgets import LocationFormField
from puv.settings import GMAP_JS, USE_ADDR
from puv.poll.utils import grab_urls

class PollForm(djangoforms.ModelForm):
    created_by = forms.CharField(max_length = 100, required=True,
                                 widget=forms.widgets.TextInput(attrs={'size':53}))
    email = forms.CharField(max_length = 100, required=False,
                            widget=forms.widgets.TextInput(attrs={'size':58}))
    question = forms.CharField(max_length = 100, required=True,
                     widget=forms.widgets.Textarea(attrs={'rows':2, 
                                                          'cols':60}))    
    locations = forms.IntegerField(widget=forms.widgets.HiddenInput(), required=False)

    class Meta:
        model = models.Poll
#        exclude = ['created_by']
 
    def _generate_js(self):
        """ Generate javascript based on locations in poll """
        return GMAP_JS

    genjs = property(_generate_js)


class ChoiceForm(forms.Form):
    location = LocationFormField()
    choice = forms.CharField(max_length = 100,
                             widget=forms.widgets.TextInput(attrs={'size':60}))
    address = forms.CharField(widget=forms.widgets.HiddenInput())

    class Meta:
        ordering = ['votes']

    def __init__(self, poll=None, *args, **kwargs):
        self.poll = poll
        super(ChoiceForm, self).__init__(*args, **kwargs)
        
    def save(self):
        cleaned = super(ChoiceForm, self).clean()
        choice = cleaned.get('choice','')
        url = None
        if choice == USE_ADDR:
            choice = ''
        else:
            urls = grab_urls(choice)
            if urls:
                for url in urls:
                    choice = choice.replace(url,'')
                url = urls[0]

        entry = models.Choice(poll = self.poll, 
                              choice = choice,
                              location = cleaned.get('location',''),
                              address = cleaned.get('address',''),
                              url = url)
        entry.put()
        


gaepuv/puv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="keywords" content="place you vote, space and time, vote, meeting scheduler, meeting scheduling, meeting, organiser, scheduling, schedule, agenda, maps, places, Android, mobile, Facebook plugin, doodle poll, meet-o-matic, timetable, calendar, appointment, date, coordinate, poll, meet, lunch, dinner, workshop, team, weekend, event, invitation, online" />
<meta name="description" content="placeUvote helps you to schedule meetings and other appointments, create polls related to places or just share your marked maps with friends. placeUvote is simple, quick, free and requires no registration. Simply set up a poll, send a link to all participants, watch progress online, and finally choose the most suitable place and date. like Doodle poll or meet-o-matic but with places, facebook plugin and mobile - Android client as well." />
<meta name="copyright" content="Apache licensed open source from placeUvote" />
<title>
{% block title %}
Page title
{% endblock %}
</title>
<link rel="shortcut icon" href="/media/favicon.ico" type="image/x-icon" /> 
<link href="/media/puv.css" type="text/css" rel="stylesheet" />
{% block media %}{% endblock %}
<style type="text/css"><!-- body { padding: 0px; margin: 0px;} --></style>
</head>

<body id="usual">
<div id="header">
<h1>placeUvote</h1>
</div>
<!-- div id="headertick">&nbsp;</div -->


<div id="topnav">
{% block topnav %}
<ul>
<li><a href="/" class="link-on">Home</a></li>
<li><a href="/create/">Create a poll</a></li>
<li><a href="/vote/">Vote in polls</a></li>
<li><a href="/results/">Polls results</a></li>
</ul>
{% endblock %}
</div>

<div id="contents">
<div id="breadcrumbs">{% block crumbs %}{% endblock %}</div>

{% block contents %}
Main page content
{% endblock %}
</div>
<div id="topnavbottom"><p><a href="http://www.apache.org/licenses/LICENSE-2.0">apache 2.0 license</a> <img src="/media/copyleft.png" alt="copyleft" /> 2010 placeUvote  
<a href="https://bitbucket.org/edcrewe/placeuvote/issues/new">Feedback</a>
<a href="http://code.google.com/appengine/terms.html" style="float:right" ><img src="/media/gaelogo.gif" alt="Powered by Google App Engine" /></a>
</p></div>
</body>
</html>

gaepuv/puv/templates/create.html
{% extends 'base.html' %}

{% block title %}
Create a new poll
{% endblock %}

{% block media %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script> 
<script type="text/javascript" src="/media/jquery.datepick.js"></script>
<link href="/media/jquery.datepick.css" type="text/css" rel="stylesheet" />

{% for js in genjs %}
{{ js|safe }}
{% endfor %}
{% endblock %}

{% block topnav %}
<ul>
<li><a href="/">Home</a></li>
<li><a href="/create/" class="link-on">Create a poll</a></li>
<li><a href="/vote/">Vote in polls</a></li>
<li><a href="/results/">Polls results</a></li>
</ul>
{% endblock %}
{% block crumbs %}<a href="/">Home</a>&gt; Create a new poll{% endblock %}

{% block contents %}
<form action="." method="post" id="id_createpoll_form">
{% if pollform.errors %}
<div class="error">{{ pollform.errors }}</div>
{% endif %}

<fieldset>
<legend>Your details</legend>
{% if login %} 
<p>Please {{ login|safe }} or fill in your name and email<br />
(Note: that registered users can retain a set of polls they have created 
and re-edit or reuse them)
</p>
{% endif %}

<label id="id_created_by_label">Your name:</label>
<span class="error" id="id_created_by_error"></span>
{{ pollform.created_by }}<br />
<label id="id_email_label">Email:</label>
<span class="error" id="id_email_error"></span>
{{ pollform.email }}<br />
</fieldset>
<br />

<fieldset>
<legend>Poll</legend>
<label id="id_question_label">Question:</label><br />
<span class="error" id="id_question_error"></span>
{{ pollform.question }}
<input type="hidden" name="locations" id="id_locations" value="{{ locations }}" />
<div id="id_location_inputs">
<span class="error" id="id_locations_error"></span>
{% for form in choiceforms %}
<div id="id_loc_line{{ forloop.counter0}}">
<img src="/media/marker/green{{ forloop.counter }}.png" alt="{{ forloop.counter }}. " />
{{ form.location }}{{ form.address }}{{ form.choice }}
<div class="markerinfo">
    <span id="id_address{{ forloop.counter0 }}"></span>
    <span id="id_info{{ forloop.counter0 }}"></span>
</div>
</div> 
{% endfor %}
</div>
<p>
<button type="button" onclick="javascript:add_marker();" id="id_add_location"><img src="/media/plus.png" alt="add a marker" class="buttonimg" /></button>  
<button type="button" onclick="javascript:remove_marker();" id="id_remove_location"><img src="/media/minus.png" alt="remove a marker" class="buttonimg" /></button>  
Add or remove a place marker</p>
<div id="id_date_inputs"></div>
<span id="id_dates_label">Enter a list of dates if you wish:</span><br />
<input type="text" id="id_date_text" name="date_text" size="60" />
<div style="display: none;">
<img id="calImg" src="/media/calendar.gif" alt="Toggle calendar popup" class="trigger" />
</div>
<p class="markerinfo">
{{ pollform.private }} hide from listings  
{{ pollform.anonymous }} anonymous voting
{{ pollform.onechoice }} only one choice allowed</p> 
<span style="float:right">Create the poll <input type="submit" name="createpoll" id="id_createpoll" value="Submit" /></span> 
</fieldset>
</form>
<br />
<form method="post" action="" id="id_move_form">
<fieldset>
<legend>Click and drag to move marker(s), or move them using an address</legend>
    <label id="id_address_move_label" class="bottomlabel">Address:</label>
	  <input type="text" name="address_move" id="id_address_move" value="" size="50" />
	  <select name="select_move" id="id_select_move">
             <option value="all">all markers</option>
             <option value="0">-- 1 --</option>
             <option value="1">-- 2 --</option>
             <option value="2">-- 3 --</option>
	  </select>   
<button type="button" onclick="javascript:showAddress(map, markers);"  id="id_move"><img src="/media/arrow.png" alt="move marker(s)" class="buttonimg" /></button> Move 
<div class="markerinfo">Enter the address or post / zip code and select the marker, to move it</div>
</fieldset>
</form>

<div id="map_default"></div>

{% endblock %}

gaepuv/puv/templates/index.html
{% extends 'base.html' %}

{% block title %}
placeUvote Home
{% endblock %}

{% block contents %}
<div id="main">

<div id="content">
<h2>placeUvote home</h2>

<p><a href="/create/">Create a poll</a> or vote in an existing poll below,
see the example <a href="/poll/agpwbGFjZXV2b3RlcgwLEgRQb2xsGOr7Aww/">polls</a>
and <a href="/poll/agpwbGFjZXV2b3RlcgwLEgRQb2xsGLmUAQw/results/">results</a> on the right.</p>

<h3><a href="/create/">Create a poll</a></h3>

<p><strong>question ?</strong> Enter your name and the question you want decided, add your email to be mailed with a link to the poll.</p>

<p><strong>move -></strong> Type an address, country, landmark, post / zip code etc. in the address box, 
next to the map, and press 'all markers' -> Move to jump to your starting location. 
</p>

<p><strong>mark &#x2610;</strong> To create the poll just use the + / - buttons to add markers to the map and 
drag them into position, or use the address box again with the numbered marker selected. 
The nearest address is used if you do not enter one into the location box.<br />
If you wish you can paste links, as well as the choice name, into the marker numbered location boxes.</p>

<p><strong>date #</strong> If you are using placeUvote to arrange a meeting you can add some dates to choose from by clicking in the date box. Select from the calendar that pops up.</p>

<p><strong>vote &#x2611;</strong> When you are done you can tick if you want your poll private, anonymous or single choice only.
Now submit the poll and it is created. Tick to vote for your choices, and submit to see your first results.</p>

<h3><a href="/vote/">Vote in a recent poll</a></h3>
<ol>
{% for poll in polls %}
<li><a href="{{poll.get_absolute_url}}">{{poll.question}}</a>
<span class="markerinfo">created on {{poll.created_on|date}}</span>
</li>
{% endfor %}
{% if not polls %}<li>Sorry no public polls were found</li>{% endif %}
</ol>
</div>

<div id="advert">
<div id="questionadvert">
<p><a href="/poll/agpwbGFjZXV2b3RlcgwLEgRQb2xsGJnsAww/">Which hotel shall we stay in when we visit Naples?</a></p>
<p><a href="/poll/agpwbGFjZXV2b3RlcgwLEgRQb2xsGOr7Aww/">Where is the best graffiti in Bristol?</a></p> 
<p><a href="/poll/agpwbGFjZXV2b3RlcgwLEgRQb2xsGLmUAQw/results/">Lets meet up for a meal next month</a></p>
<p><a href="/poll/agpwbGFjZXV2b3RlcgwLEgRQb2xsGOHRBAw/">Which is the ugliest?</a></p>
</div>
<div id="whiteadvert">
<p>If you want to decide on somewhere, arrange a meeting from a choice of venues, or just share places with friends, you can decide together with placeUvote.</p>
<p>Its like <a href="http://www.doodle.com/">Doodle poll</a> or <a href="http://www.meetomatic.com">Meet-o-matic</a> but with locations too.</p>
<h4>Forthcoming Features:</h4>
<ul>
<li>Mobile Android client</li>
<li>Facebook plugin</li>
<li>OpenID registration for MyPolls management</li>
<li>HTML5 iPhone friendly version</li>
</ul>
</div>
</div>

</div>

{% endblock %}

gaepuv/puv/templates/poll_details.html
{% extends 'base.html' %}

{% block title %}
{{poll.question}}
{% endblock %}

{% block media %}
{% for js in genjs %}
{{ js|safe }}
{% endfor %}
{% endblock %}

{% block topnav %}
<ul>
<li><a href="/">Home</a></li>
<li><a href="/create/">Create a poll</a></li>
<li><a href="/vote/" class="link-on">Vote in polls</a></li>
<li><a href="/results/">Polls results</a></li>
</ul>
{% endblock %}

{% block crumbs %}<a href="/">Home</a>
&gt; Vote in poll {{poll.question}}
&gt; <a href="/poll/{{poll.key}}/results/">Results of poll {{poll.question}}</a>
{% endblock %}

{% block contents %}
<div class="poll">
<h5>{{poll.question}}</h5> 
<p class="markerinfo">Poll created on {{poll.created_on|date}} by {{poll.created_by}}</p>
</div>
<form action="." method="post">
{% if not poll.anonymous %}
<fieldset>
<label>Your name:</label>
<input type="text" name="created_by"  size="40" id="id_created_by" value="{{ created_by }}" />
{% endif %}
{% if nochoice %}
<p>{{ nochoice.choice }}</p>
{% else %}
{% for choice in choices %}
<br /><img src="/media/marker/green{{ forloop.counter }}.png" alt="{{ forloop.counter }}. " /> <input type="{{ input_type }}" name="location" value="{{ choice.key }}" />
{{ choice|safe }}
</li>
{% endfor %}
{% endif %}
{% if dates %}
<ol>
{% for date in dates %}
<li class="choice"><input type="{{ input_type }}" name="date" value="{{ date.key }}" />
{{ date.datetime|date:"l, d F Y" }}</li>
{% endfor %}
</ol>
{% endif %}
<input type="submit" name="dovote" value="Choose" />
</fieldset>
</form>

<div id="map_default">
</div>

<br />

{% endblock %}

gaepuv/puv/templates/poll_results.html
{% extends 'base.html' %}

{% block title %}
{{poll.question}} - results
{% endblock %}

{% block topnav %}
<ul>
<li><a href="/">Home</a></li>
<li><a href="/create/">Create a poll</a></li>
<li><a href="/vote/">Vote in polls</a></li>
<li><a href="/results/" class="link-on">Polls results</a></li>
</ul>
{% endblock %}

{% block crumbs %}<a href="/">Home</a>
&gt; <a href="/poll/{{poll.key}}/">Vote in poll {{poll.question}}</a>
&gt; Results of poll {{poll.question}}
{% endblock %}

{% block contents %}
<div class="poll">
<h5>{{poll.question}}</h5> 
<p class="markerinfo">Poll created on {{poll.created_on|date}}</p>
</div>

{% if choices %}
<br />
<table id="id_poll_location_results" summary="Ordered location results for poll {{poll.question}}">
<tr><th>votes</th><th>place</th>
{% if not poll.anonymous %}<th>voters</th>{% endif %}
</tr>
{% for choice in choices %}
  <tr class="{% if forloop.counter|divisibleby:2 %}even{% else %}odd{% endif %}" id="id_location_{{ forloop.counter }}">
<td>{{choice.votes}}</td><td>{{ choice|safe }}</td>
{% if not poll.anonymous %}
<td>{% for voter in choice.voter_set %}{{ voter.created_by }}{% if not forloop.last %}, {% endif %}{% endfor %}
</td> 
{% endif %}
</tr>
{% endfor %}
</table>
{% endif %}

{% if dates %}
<br /><br />
<table id="id_poll_date_results" summary="Ordered date results for poll {{poll.question}}">
<tr><th>votes</th><th>date</th>
{% if not poll.anonymous %}<th>voters</th>{% endif %}
</tr>
{% for choice in dates %}
  <tr class="{% if forloop.counter|divisibleby:2 %}even{% else %}odd{% endif %}" id="id_date_{{ choice.datetime|date:"Y-m-d" }}">
<td>{{choice.votes}}</td><td> {{ choice.datetime|date:"l, d F Y" }} </td>
{% if not poll.anonymous %}
<td>{% for voter in choice.voter_set %}{{ voter.created_by }}{% if not forloop.last %}, {% endif %}{% endfor %}
</td> 
{% endif %}
</tr>
{% endfor %}
</table>
{% endif %}

<p>Last vote cast on {{ poll.last_vote|date }}</p>
{% endblock %}

gaepuv/puv/templates/results_index.html
{% extends 'base.html' %}

{% block title %}
placeUvote Results
{% endblock %}

{% block topnav %}
<ul>
<li><a href="/">Home</a></li>
<li><a href="/create/">Create a poll</a></li>
<li><a href="/vote/">Vote in polls</a></li>
<li><a href="/results/" class="link-on">Polls results</a></li>
</ul>
{% endblock %}

{% block crumbs %}<a href="/">Home</a>&gt; Select poll results{% endblock %}

{% block contents %}

<h5>Poll results</h5>

<ol>
{% for poll in polls %}
<li><a href="{{poll.get_absolute_url}}results">{{poll.question}}</a>
<span class="markerinfo">created on {{poll.created_on|date}}</span>
</li>
{% endfor %}
</ol>

{% endblock %}

gaepuv/puv/templates/vote_index.html
{% extends 'base.html' %}

{% block title %}
placeUvote Home
{% endblock %}


{% block topnav %}
<ul>
<li><a href="/">Home</a></li>
<li><a href="/create/">Create a poll</a></li>
<li><a href="/vote/" class="link-on">Vote in polls</a></li>
<li><a href="/results/">Poll results</a></li>
</ul>
{% endblock %}

{% block crumbs %}<a href="/">Home</a>&gt; Select poll to vote in{% endblock %}

{% block contents %}

<h5>Vote in a poll</h5>

<ol>
{% for poll in polls %}
<li><a href="{{ poll.get_absolute_url }}">{{poll.question}}</a>
<span class="markerinfo">created on {{poll.created_on|date}}</span>
</li>
{% endfor %}
</ol>

{% endblock %}